"""
Mapping utilities for converting between API-specific and standardized formats.
"""

from travel_connector.models.hotel import HotelAmenity
from travel_connector.models.room import RoomAmenity

# Mapping from Ratehawk amenity names to standardized HotelAmenity values
amenity_mapping = {
    # Hotel amenities
    "wifi": HotelAmenity.WIFI,
    "internet": HotelAmenity.WIFI,
    "free wifi": HotelAmenity.WIFI,
    "pool": HotelAmenity.POOL,
    "swimming pool": HotelAmenity.POOL,
    "outdoor pool": HotelAmenity.POOL,
    "indoor pool": HotelAmenity.POOL,
    "fitness": HotelAmenity.FITNESS_CENTER,
    "fitness center": HotelAmenity.FITNESS_CENTER,
    "gym": HotelAmenity.FITNESS_CENTER,
    "restaurant": HotelAmenity.RESTAURANT,
    "bar": HotelAmenity.BAR,
    "lounge": HotelAmenity.BAR,
    "spa": HotelAmenity.SPA,
    "wellness": HotelAmenity.SPA,
    "massage": HotelAmenity.SPA,
    "room service": HotelAmenity.ROOM_SERVICE,
    "parking": HotelAmenity.PARKING,
    "free parking": HotelAmenity.PARKING,
    "business center": HotelAmenity.BUSINESS_CENTER,
    "conference": HotelAmenity.BUSINESS_CENTER,
    "meeting rooms": HotelAmenity.BUSINESS_CENTER,
    "breakfast": HotelAmenity.BREAKFAST,
    "free breakfast": HotelAmenity.BREAKFAST,
    "laundry": HotelAmenity.LAUNDRY,
    "dry cleaning": HotelAmenity.LAUNDRY,
    "shuttle": HotelAmenity.SHUTTLE,
    "airport shuttle": HotelAmenity.SHUTTLE,
    "concierge": HotelAmenity.CONCIERGE,
    "reception": HotelAmenity.CONCIERGE,
    "air conditioning": HotelAmenity.AIR_CONDITIONING,
    "ac": HotelAmenity.AIR_CONDITIONING,
    "accessible": HotelAmenity.DISABLED_ACCESS,
    "wheelchair accessible": HotelAmenity.DISABLED_ACCESS,
    "disability-friendly": HotelAmenity.DISABLED_ACCESS,
    "pet friendly": HotelAmenity.PET_FRIENDLY,
    "pets allowed": HotelAmenity.PET_FRIENDLY,
    "beach": HotelAmenity.BEACH_ACCESS,
    "beach access": HotelAmenity.BEACH_ACCESS,
    "beachfront": HotelAmenity.BEACH_ACCESS,
    "ski": HotelAmenity.SKI_ACCESS,
    "ski storage": HotelAmenity.SKI_ACCESS,
    "ski-to-door": HotelAmenity.SKI_ACCESS,
    
    # Room amenities
    "room air conditioning": RoomAmenity.AIR_CONDITIONING,
    "tv": RoomAmenity.TV,
    "television": RoomAmenity.TV,
    "flat-screen tv": RoomAmenity.TV,
    "satellite tv": RoomAmenity.TV,
    "room wifi": RoomAmenity.WIFI,
    "free wifi in room": RoomAmenity.WIFI,
    "minibar": RoomAmenity.MINI_BAR,
    "mini-bar": RoomAmenity.MINI_BAR,
    "refrigerator": RoomAmenity.MINI_BAR,
    "safe": RoomAmenity.SAFE,
    "safety deposit box": RoomAmenity.SAFE,
    "hairdryer": RoomAmenity.HAIRDRYER,
    "hair dryer": RoomAmenity.HAIRDRYER,
    "bathtub": RoomAmenity.BATHTUB,
    "bath": RoomAmenity.BATHTUB,
    "shower": RoomAmenity.SHOWER,
    "balcony": RoomAmenity.BALCONY,
    "terrace": RoomAmenity.BALCONY,
    "kitchen": RoomAmenity.KITCHEN,
    "kitchenette": RoomAmenity.KITCHEN,
    "coffee machine": RoomAmenity.COFFEE_MACHINE,
    "coffee maker": RoomAmenity.COFFEE_MACHINE,
    "tea/coffee maker": RoomAmenity.COFFEE_MACHINE,
    "iron": RoomAmenity.IRON,
    "ironing facilities": RoomAmenity.IRON,
    "desk": RoomAmenity.DESK,
    "work desk": RoomAmenity.DESK,
    "telephone": RoomAmenity.TELEPHONE,
    "phone": RoomAmenity.TELEPHONE,
    "bathrobes": RoomAmenity.BATH_ROBES,
    "bath robes": RoomAmenity.BATH_ROBES,
    "sea view": RoomAmenity.SEA_VIEW,
    "ocean view": RoomAmenity.SEA_VIEW,
    "mountain view": RoomAmenity.MOUNTAIN_VIEW,
    "city view": RoomAmenity.CITY_VIEW
}

# Mapping for other data source amenities can be added here
